// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package sqlc

import (
	"context"
)

type Querier interface {
	CreateTodo(ctx context.Context, title string) (Todo, error)
	DeleteTodo(ctx context.Context, id int32) error
	GetTodo(ctx context.Context, id int32) (Todo, error)
	ListTodos(ctx context.Context) ([]Todo, error)
}

var _ Querier = (*Queries)(nil)
